FROM ghcr.io/jensberg047/jensberg047.github.io.base:main
WORKDIR /usr/src/app
RUN apt-get install -y gpg software-properties-common pandoc
RUN gpg --keyserver keyserver.ubuntu.com --recv-key E298A3A825C0D65DFD57CBB651716619E084DAB9
RUN gpg -a --export E298A3A825C0D65DFD57CBB651716619E084DAB9 | apt-key add -
RUN apt-add-repository "deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/"
RUN apt-get update -y && apt-get install -y r-base-dev curl libcurl4-openssl-dev libxml2-dev libssl-dev
RUN R --version
RUN R -e 'install.packages("rmarkdown", dependencies=TRUE, repos="http://cran.rstudio.com/")'
RUN R -e 'install.packages("distill", dependencies=TRUE, repos="http://cran.rstudio.com/")'
RUN R -e 'install.packages("postcards", dependencies=TRUE, repos="http://cran.rstudio.com/")'
