FROM r-base:latest
WORKDIR /usr/src/app
RUN R -e 'install.packages("rmarkdown", dependencies=TRUE, repos="http://cran.rstudio.com/")'
RUN R -e 'install.packages("distill", dependencies=TRUE, repos="http://cran.rstudio.com/")'
RUN R -e 'install.packages("postcards", dependencies=TRUE, repos="http://cran.rstudio.com/")'